import { betterAuth } from "better-auth";
import { username } from "better-auth/plugins";
import { convex, crossDomain } from "@convex-dev/better-auth/plugins";
import { createClient } from "@convex-dev/better-auth";
import { components } from "./_generated/api.js";
import authConfig from "./auth.config.js";
import type { DataModel } from "./_generated/dataModel.js";
import type { GenericCtx } from "@convex-dev/better-auth";
import {
  verificationEmailHtml,
  resetPasswordEmailHtml,
} from "./emails.js";

const env =
  (globalThis as { process?: { env?: Record<string, string | undefined> } })
    .process?.env ?? {};
const DEFAULT_WEB_ORIGINS = [
  "http://localhost:5173",
  "http://127.0.0.1:5173",
];

function parseOrigins(value: string | undefined) {
  if (!value) return [];

  return value
    .split(",")
    .map((origin) => origin.trim())
    .filter((origin) => origin.length > 0);
}

const siteUrl =
  env.CONVEX_SITE_URL ?? env.SITE_URL ?? "http://localhost:3210";
const configuredWebOrigins = parseOrigins(env.SITE_URL);
const primaryWebOrigin = configuredWebOrigins[0] ?? DEFAULT_WEB_ORIGINS[0];
const trustedWebOrigins = Array.from(
  new Set(
    configuredWebOrigins.length > 0
      ? [...configuredWebOrigins, ...DEFAULT_WEB_ORIGINS]
      : DEFAULT_WEB_ORIGINS,
  ),
);

// Cast needed: offline stub types lack component API shape.
// Proper types are generated by `npx convex dev`.
export const authComponent = createClient<DataModel>(
  (components as any).betterAuth,
);

export const createAuth = (ctx: GenericCtx<DataModel>) => {
  return betterAuth({
    baseURL: siteUrl,
    trustedOrigins: trustedWebOrigins,
    database: authComponent.adapter(ctx),
    emailAndPassword: {
      enabled: true,
      requireEmailVerification: true,
      sendResetPassword: async ({ user, url }) => {
        const rawResetUrl = new URL(url);
        const token = rawResetUrl.pathname.split("/").pop();
        const appResetUrl = new URL("/reset-password", primaryWebOrigin);
        if (token) {
          appResetUrl.searchParams.set("token", token);
        }
        await (ctx as any).runAction("sendEmail:sendEmail", {
          to: user.email,
          subject: "Reset your password",
          html: resetPasswordEmailHtml(appResetUrl.toString()),
        });
      },
    },
    emailVerification: {
      sendVerificationEmail: async ({ user, url }) => {
        await (ctx as any).runAction("sendEmail:sendEmail", {
          to: user.email,
          subject: "Verify your email",
          html: verificationEmailHtml(url),
        });
      },
      sendOnSignUp: true,
      autoSignInAfterVerification: true,
    },
    plugins: [
      crossDomain({ siteUrl: primaryWebOrigin }),
      username(),
      convex({ authConfig }),
    ],
  });
};
