export const ROTATING_HINTS = [
  "Always attack with 3 troops when you can",
  "Capture an entire continent for bonus troops",
  "Press H to open the game history",
  "Press C to open and close your cards",
  "Press ? to view available keyboard shortcuts",
  "Press I to better explore the map",
  "Use the arrow keys to increase/decrease troop counts",
  "Use the number row to set troop count, dice count, etc",
  "Arrow keys adjust troop counts during attacks and fortifies",
  "Click on a player to highlight their territories",
  "Strengthen borders first before interior territories",
  "Don’t overextend; leaving 1 troop behind invites easy takebacks",
  "Before attacking, count how many reinforcements you’ll need to hold gains",
  "Trade cards as soon as you can if it helps you take (or hold) a continent",
  "Use attacks to eliminate a player when it earns you their cards",
  "Stop attacking early if your main stack drops too low to defend",
  "Use fortifies to consolidate into strong stacks",
  "When defending a continent, keep extra troops on chokepoints",
  "Try to reduce the number of borders you must defend",
  "Watch opponents’ card counts. Someone at 4 cards can likely trade",
  "Plan your turn around your best attack lane, not scattered small attacks",
  "Pay attention to who benefits from your attacks. Don’t do someone else’s work",
  "Keep an eye on your opponent's territories. Don't let them hold entire continents",
  "You get 1 extra troop per 3 territories each turn"
];
