import { betterAuth } from "better-auth";
import { convex } from "@convex-dev/better-auth/plugins";
import { createClient } from "@convex-dev/better-auth";
import { components } from "./_generated/api.js";
import authConfig from "./auth.config.js";
import type { DataModel } from "./_generated/dataModel.js";
import type { GenericCtx } from "@convex-dev/better-auth";
import {
  resend,
  fromAddress,
  verificationEmailHtml,
  resetPasswordEmailHtml,
} from "./emails.js";

const siteUrl = process.env.SITE_URL!;

// Cast needed: offline stub types lack component API shape.
// Proper types are generated by `npx convex dev`.
export const authComponent = createClient<DataModel>(
  components.betterAuth as any,
);

export const createAuth = (ctx: GenericCtx<DataModel>) => {
  return betterAuth({
    baseURL: siteUrl,
    database: authComponent.adapter(ctx),
    emailAndPassword: {
      enabled: true,
      requireEmailVerification: true,
      sendResetPassword: async ({ user, url }) => {
        await resend.sendEmail(ctx as any, {
          from: fromAddress,
          to: user.email,
          subject: "Reset your password",
          html: resetPasswordEmailHtml(url),
        });
      },
    },
    emailVerification: {
      sendVerificationEmail: async ({ user, url }) => {
        await resend.sendEmail(ctx as any, {
          from: fromAddress,
          to: user.email,
          subject: "Verify your email",
          html: verificationEmailHtml(url),
        });
      },
      sendOnSignUp: true,
      autoSignInAfterVerification: true,
    },
    plugins: [convex({ authConfig })],
  });
};
