import { betterAuth } from "better-auth";
import { convex } from "@convex-dev/better-auth/plugins";
import { createClient } from "@convex-dev/better-auth";
import { components } from "./_generated/api.js";
import authConfig from "./auth.config.js";
import type { DataModel } from "./_generated/dataModel.js";
import type { GenericCtx } from "@convex-dev/better-auth";

const siteUrl = process.env.SITE_URL!;

// Cast needed: offline stub types lack component API shape.
// Proper types are generated by `npx convex dev`.
export const authComponent = createClient<DataModel>(
  components.betterAuth as any,
);

export const createAuth = (ctx: GenericCtx<DataModel>) => {
  return betterAuth({
    baseURL: siteUrl,
    database: authComponent.adapter(ctx),
    emailAndPassword: {
      enabled: true,
      requireEmailVerification: false,
    },
    plugins: [convex({ authConfig })],
  });
};
