import { betterAuth } from "better-auth";
import { username } from "better-auth/plugins";
import { convex, crossDomain } from "@convex-dev/better-auth/plugins";
import { createClient } from "@convex-dev/better-auth";
import { components } from "./_generated/api.js";
import authConfig from "./auth.config.js";
import type { DataModel } from "./_generated/dataModel.js";
import type { GenericCtx } from "@convex-dev/better-auth";
import {
  verificationEmailHtml,
  resetPasswordEmailHtml,
} from "./emails.js";

const env =
  (globalThis as { process?: { env?: Record<string, string | undefined> } })
    .process?.env ?? {};
const siteUrl =
  env.CONVEX_SITE_URL ?? env.SITE_URL ?? "http://localhost:3210";
const webOrigin =
  env.VITE_SITE_URL ?? env.WEB_ORIGIN ?? env.SITE_URL ?? "http://localhost:5173";

// Cast needed: offline stub types lack component API shape.
// Proper types are generated by `npx convex dev`.
export const authComponent = createClient<DataModel>(
  (components as any).betterAuth,
);

export const createAuth = (ctx: GenericCtx<DataModel>) => {
  return betterAuth({
    baseURL: siteUrl,
    trustedOrigins: [webOrigin],
    database: authComponent.adapter(ctx),
    emailAndPassword: {
      enabled: true,
      requireEmailVerification: true,
      sendResetPassword: async ({ user, url }) => {
        await (ctx as any).runAction("sendEmail:sendEmail", {
          to: user.email,
          subject: "Reset your password",
          html: resetPasswordEmailHtml(url),
        });
      },
    },
    emailVerification: {
      sendVerificationEmail: async ({ user, url }) => {
        await (ctx as any).runAction("sendEmail:sendEmail", {
          to: user.email,
          subject: "Verify your email",
          html: verificationEmailHtml(url),
        });
      },
      sendOnSignUp: true,
      autoSignInAfterVerification: true,
    },
    plugins: [crossDomain({ siteUrl: webOrigin }), username(), convex({ authConfig })],
  });
};
